name: Metrics
on:
  # Schedule updates (every 3rd hour)
  schedule: [{cron: "0 0/12 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: deapdaru
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Calcutta
          plugin_skyline: yes
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5
          plugin_skyline_year: current-year
